### ISSUE TITLE
How to get data from collections

### ISSUE THREAD

**Issue by sachin-siwal** [EngrAhsanAli/MeteorDDP#10]
When subscribing, I am getting data in dataAdded event for the first time. 
========
         var allDocuments = [MeteorDocument]()
        TaMeteor.shared.meteor.subscribe("name", params:  [5], collectionName: "cName", callback: { (event, doc) in
            print("Event received ", event)
            print("Document received ", doc)
            switch event {
            case .dataAdded:
                print(doc.fields ?? "")
                allDocuments.append(doc)
                break

            case .dataChange:
                //print(doc.fields ?? "")
                break

            case .dataRemove:
                break
            }
            
        }) {
            print(" Subscription Done")
}
==============
But when I am subscribing it again, Its not entering into the block, My question is: How to get data from the collection on the second call?

**Comment by EngrAhsanAli** [comment]
Yes. You need to understand how meteor works in subscribing and unsubscribing stuff.

If you subscribe to some collection, like the name of the collection (not subscription name) "my_messages", when you need to resubscribe this (maybe with the same subscription name or different but using same collection) you need to unsub this first in a callback to make sure, the previous sub is dead and all callbacks are finished, then you need to subscribe that again.

Please reach out to me on my email directly in case you need further help regarding this issue.

**Comment by sachin-siwal** [comment]
So we need to unsubscribe from the existing subscription before subscribing? 
If I just want to take data from collections is there any other way of fetching data? except using subscribe?
