### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by derwaldgeist** [EngrAhsanAli/MeteorDDP#14]
I tried to run the sample app, but ran into a build error. This could be fixed by adding some lines to the Pod file:

```pod
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
```

However, when I finally got it running, nothing happened. Not a single connection was possible, nor a login. It would be nice to know if this lib actually works and is maintained or if I should look for another solution.

**Comment by derwaldgeist** [comment]
Update: After I switched from Starscream to .webSocketTask, it worked.

**Comment by EngrAhsanAli** [comment]
Thank you for your update and considering this contribution. Feel free to open new threads if required any assistance.

**Comment by derwaldgeist** [comment]
Thanks for the feedback. So I assume you're still maintaining the library? In this case, it would be nice if you could provide some feedback on the question in https://github.com/EngrAhsanAli/MeteorDDP/issues/1. Were these "instabilities" resolved in the meantime?

BTW: I managed to get the library up and running on visionOS. Would you accept PRs for this?

One issue I am currently trying to resolve is that the library automatically logs the user out once the user has been logged in if I try to log in on startup, because it executes this line:

https://github.com/EngrAhsanAli/MeteorDDP/blob/master/MeteorDDP/Classes/Meteor/Meteor%20Client/MeteorClient.swift#L321

I wonder why this happens although I can see in the logs that the login itself was successful? Why is `.logout()` called in the first place, if the auto-login did not succeed?
