### ISSUE TITLE
No such module 'MeteorDDP' with Carthage

### ISSUE THREAD

**Issue by crapthings** [EngrAhsanAli/MeteorDDP#3]
i'm new to ios native dev, and i'm following get start but stuck here

![image](https://user-images.githubusercontent.com/1147704/93734552-4a06fb00-fc0c-11ea-9d5e-7a958dbbe87d.png)

![image](https://user-images.githubusercontent.com/1147704/93732878-ee397380-fc05-11ea-99a1-f6c53260b13a.png)

**Comment by EngrAhsanAli** [comment]
Thanks for using MeteorDDP.
Please follow the link to resolve this problem. 
https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there

**Comment by crapthings** [comment]
i've tried marked answer but still same

![image](https://user-images.githubusercontent.com/1147704/93741884-c525dc80-fc1f-11ea-8173-a11a0720661c.png)

![image](https://user-images.githubusercontent.com/1147704/93742118-251c8300-fc20-11ea-9dc4-5714d87bcc0e.png)

**Comment by crapthings** [comment]
tried pod

![image](https://user-images.githubusercontent.com/1147704/93742489-c572a780-fc20-11ea-90ed-26d28462c9ee.png)

maybe my xcode is too old

![image](https://user-images.githubusercontent.com/1147704/93742524-d3c0c380-fc20-11ea-8262-7ab1c0fdfb84.png)

**Comment by crapthings** [comment]
pod works

after 

```
platform :ios, '10.0'

target 'meteorapp101' do
  use_frameworks!
pod 'MeteorDDP'
end
```
